### ISSUE TITLE
light theme variant of new monofile logo

### ISSUE THREAD

**Issue by Jack5079** [mollersuite/monofile#33]

**Comment by nbitzz** [comment]
We'd need to convert all icons imported through <img> to <svg>s, but we should probably figure out a cleaner way to do this first: might be a good idea to resolve #36 first if possible though (or not and we stick with Fluent /shrug)

**Comment by nbitzz** [comment]
Also should set up some actual decent method of theming through a palette like:
```css
:root {
    --background: linear_gradient();
    --primary: ;
    --secondary: ;
    --crust: ;
    --surface: ;
}
```
idk, i'll figure it out /shrug
